### ISSUE TITLE
`export type *` syntax.

### ISSUE THREAD

**Issue by onehorsetown** [nirtamir2/eslint-plugin-sort-export-all#16]
I know this plugin does not claim to have typescript support and up until TypeScript 5.0 there was no conflicting syntax.  However TypeScript 5.0 did introduce a new `export type *` [construct](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#support-for-export-type).

The fallout of this is that this plugin's `sort-export-all/sort-export-all` rule now conflicts with the [eslint-plugin-sort-exports](https://www.npmjs.com/package/eslint-plugin-sort-exports) `sort-exports/sort-exports` rule.  `sort-exports/sort-exports` is TypeScript aware and, by default, places `type` exports first.

This plugin wants to sort purely alphabetically, while `eslint-plugin-sort-exports` organizes the exports by type.  This creates a circular conflict with code like, for example:

```
export * from './constants.js';
export type * from './types.js';
export * from './utils.js';
```

<img width="704" alt="types" src="https://user-images.githubusercontent.com/6931779/234382807-ff1d303a-fe60-49f2-8c32-ff24a377417d.png">

**Comment by nirtamir2** [comment]
Thanks!
Fixed in v1.3.0
